import { query } from '../../db';

async function migrate() {
  await query(`
    CREATE TABLE IF NOT EXISTS crew_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name TEXT NOT NULL,
      last_name TEXT NOT NULL,
      age INTEGER,
      profession TEXT NOT NULL,
      description TEXT NOT NULL,
      image TEXT NOT NULL
    );
  `);
}

migrate()
  .then(() => process.exit(0))
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error('Migration 004 failed:', err);
    process.exit(1);
  });


