import { query } from '../../db';

async function migrate() {
  await query(`
    CREATE TABLE IF NOT EXISTS articles (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      url TEXT NOT NULL,
      image TEXT NOT NULL
    );
  `);
}

migrate()
  .then(() => process.exit(0))
  .catch((err) => {
    // eslint-disable-next-line no-console
    console.error('Migration 005 failed:', err);
    process.exit(1);
  });


